language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
install:
  - npm install
before_script:
  - npm test
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t gistda/gnss-udp-receiver .
  - docker push gistda/gnss-udp-receiver
