language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
install:
  - npm install
before_script:
  - npm test
after_success:
  - export REPO=gistda/gnss-udp-receiver
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
