dist: trusty
sudo: required
language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
before_install:
  - npm install -g codecov
  - docker build -t gistda/gnss-udp-receiver .
install:
  - npm install
before_script:
  - npm test
  - npm run coverage
  - codecov --token=$CODECOV_TOKEN
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push gistda/gnss-udp-receiver
