language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
before_install:
  - npm install -g codecov
install:
  - npm install
before_script:
  - npm test
  - npm run coverage
  - codecov --token=$CODECOV_TOKEN
script:
  - docker build -t gistda/gnss-udp-receiver .
deploy:
  - provider: script
    script: bin/dockerhub.sh
