language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
before_install:
  - npm install -g codecov
install:
  - npm install
before_script:
  - npm test
  - npm run coverage
  - codecov --token=$CODECOV_TOKEN
script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS hub.docker.com
  - docker build -t gistda/gnss-udp-receiver .
  - docker push gistda/gnss-udp-receiver
