language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
before_install:
  - npm install -g codecov
install:
  - npm install
script:
  - npm test
  - npm run coverage
  - codecov --token=$CODECOV_TOKEN
after_success:
  - set -e
  - docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
  - ./scripts/build.sh
