language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
before_install:
  - npm install -g codecov
install:
  - npm install
before_script:
  - npm test
  - npm run coverage
  - codecov --token=$CODECOV_TOKEN
script:
  - export REPO=gistda/gnss-udp-receiver
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS hub.docker.com;
    docker push $REPO
