language: node_js
services:
  - docker
node_js:
  - "7"
env:
  - NODE_ENV=test
before_install:
  - npm install -g codecov
install:
  - npm install
before_script:
  - npm test
  - npm run coverage
  - codecov --token=$CODECOV_TOKEN
script:
  - docker build -t jiramot/gnss-udp-receiver .
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker push jiramot/gnss-udp-receiver
