version: '3'

services:
  gnss:
    build: .
    ports:
      - 3000/udp:3000/udp
    environment:
      - NODE_ENV=docker
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
