version: '3'

services:
  server:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
