version: '3'

services:
  server:
    image: gistda/gnss-udp-receiver
    ports:
      - 3000/udp:3000/udp
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
